import "@styles/globals.css";
import Menu from "@components/Menu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <Menu />
        </div>
        <div className="w-10/12 h-screen m-auto max-[1000px]:m-0 max-[1000px]:w-full">{children}</div>
      </body>
    </html>
  );
}
